volumes:
  order_management_api_local_postgres_data: {}
  order_management_api_local_postgres_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: order_management_api_local_django
    container_name: order_management_api_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    image: postgres:16
    container_name: order_management_api_local_postgres
    volumes:
      - order_management_api_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.local/.postgres
